
services:
  - type: web
    name: rezon-security-app
    env: static
    buildCommand: chmod +x ./build.sh && ./build.sh
    staticPublishPath: ./dist
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PATH
        value: /opt/render/project/node_modules/.bin:$PATH
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
