services:
  - type: web
    name: rezon-security-app
    env: static
    buildCommand: chmod +x ./build.sh && ./build.sh
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_VERSION
        value: 18
      - key: NPM_VERSION
        value: 9
      - key: PATH
        value: /opt/render/project/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:$PATH
      - key: NODE_PATH
        value: /opt/render/project/node_modules
      - key: NODE_ENV
        value: production
      - key: DEBUG
        value: vite:*
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=3600