// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bgeswpiabjjewnrperku.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJnZXN3cGlhYmpqZXducnBlcmt1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDExNjg5NzIsImV4cCI6MjA1Njc0NDk3Mn0.jEB9mQC9FfdFDckVmGwoXNjCHzImmss50jfr91BQCTk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);